### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by ftaeger** [rgevaert/puppet-pwgen#1]
Could you provide an example on how to use it to assign a random string of a predefined length to a variable in puppet?

**Comment by rgevaert** [comment]
Hello!

Unfortunately that isn't supported with this implementation.  But I added a branch 'customlength'.  I tested it. Can you confirm it suits your needs and let me know? Check the README file too. Thanks

**Comment by weshooper** [comment]
The 'customlength' works great, thanks. Also fixes an issue we were having using the module! :-)
