### ISSUE TITLE
New release with customlength?

### ISSUE THREAD

**Issue by weshooper** [rgevaert/puppet-pwgen#2]
@rgevaert Any plans to merge https://github.com/rgevaert/puppet-pwgen/commits/customlength and create a new release so it's available on forge?

**Comment by rgevaert** [comment]
@weshooper I already merged into master. I'm now setting up some small basic CI. When I get around to finishing that I'll release a new release to the forge.  Since the last time I did that many things changed for publishing to the forge. I need to have a look to that.

**Comment by weshooper** [comment]
@rgevaert lovely, thanks for that, and the module itself :)
